#!/usr/bin/env bash
# display "To infinity and beyond"."I am invincible!!!" when recieved SIGTERM signal
trap "echo I am invincible!!!" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
