#!/usr/bin/env bash
# displays "Best School" and then "Hi" on a new line.

iteration=1
while [ $iteration -le 10 ]; do
    if [ $iteration -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((iteration++))
done
