#!/usr/bin/env bash
# script to display "Best School" 9 times and after 9th iteration display "Hi"

iteration=1
while [ $iteration -le 10 ]; do
    if [ $iteration -eq 9 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((iteration++))
done
